### ISSUE TITLE
mid-v1.3 milestone- chihao

### ISSUE THREAD

**Issue by kohchihao** [CS2103-AY1819S1-T16-3/main#83]
By mid-v1.3, I should: 
- [ ] Next fxml before login
- [ ] Add username inside menubar
- [ ] username should be case insensitive
- [ ] Refactor person classes 
- [ ] logout rebase
- [ ] update addressbook.xml -> foodzoom.xml
